B3/config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      get :search
    end

    get 'category(/:name)', name: /[a-zA-Z0-9]+/ ,on: :collection, to: 'posts#category', as: :category
    get 'time(/:month)', month: /[0-9]+/, on: :collection, to: 'posts#time', as: :time
  end
  root 'posts#index'


  get 'users/register',  to: 'users#register', as: :user_register
  post 'users/register', to: 'users#create'
  get 'users/login', to: 'users#new', as: :user_login
  post 'users/login', to: 'users#login'
  get 'users/personal_page', to: 'users#personal_page', as: :personal_page
  delete 'users/logout', to: 'users#destroy', as: :user_logout

  get 'admins/register', to: 'admins#register', as: :admin_register
  post 'admins/register', to: 'admins#create'
  get 'admins/login', to: 'admins#new', as: :admin_login
  post 'admins/login', to: 'admins#login'
  delete 'admins/logout', to: 'admins#destroy', as: :admin_logout
  get 'admins/lock', to: 'admins#lock', as: :admin_lock
  get 'admins/my_check', to: 'admins#my_check', as: :my_check
  get 'admins/check_index', to: 'admins#check_index', as: :check_index
  post 'admins/check', to: 'admins#check', as: :check
  get 'admins/check_show/(/:post_id)', post_id: /[0-9]+/, to: 'admins#check_show',as: :check_show

  post 'comments/create', to: 'comments#create', as: :comment_create
  get 'comments/index', to: 'comments#index', as: :comments
  post 'comments/check', to: 'comments#check', as: :check_comments

  post 'feedbacks/create', to: 'feedbacks#create', as: :feedback_create
  get 'feedbacks/index', to: 'feedbacks#index', as: :feedbacks

end

B3/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :postable, polymorphic: true
  has_many :comments
  self.per_page = 5
  validates :title, length: {
    minimum: 3
  }
  validates :body, length: {
    minimum: 100
  }
  validates :categories, presence: true
end

B3/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :validate_search_key, only: [:search]
  before_action :require_login, only:[:new]
  def time
    @posts = Post.where(month: params[:month],post_check: true).paginate(page: params[:page])
  end

  def category
    @category = params[:name]
    @posts = Post.where(categories: @category, post_check: true).paginate(page: params[:page])
  end

  def index
    if session[:user_id]
      @username = User.find(session[:user_id]).username
    end
    @posts = Post.where(:post_check => true).paginate(page: params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.where(comment_check: true)
  end

  def new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.postable_id = session[:user_id]
    @post.postable_type = "User"
    if @post.save
      @post.update(month: @post.created_at.month)
      # 重定向到show页面
      redirect_to @post
    else
      redirect_to user_login_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      # 重定向到show页面
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def search
    if @query_string.present?
       search_result = Post.ransack(@search_criteria).result(:distinct => true)
       @posts = search_result.paginate(:page => params[:page], :per_page => 5 )
    end
  end

  private
  def post_params
    params.require(:post).permit(:admin_id, :user_id, :title, :body, :categories, :post_check, :postable_id, :postable_type)
  end

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
    @search_criteria = search_criteria(@query_string)
  end

  def search_criteria(query_string)
    { title_cont: query_string }
  end

  def require_login
    unless session[:user_id]
      redirect_to user_login_path
    end
  end
end

B3/app/helpers/posts_helper.rb
module PostsHelper
  def render_highlight_content(post,query_string)
    excerpt_cont = excerpt(post.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
end

B3/app/views/posts/_form.html.erb
<%= form_for @post do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.kindeditor :body %>
  </div>

  <div class="field">
    <%= form.label :categories %>
    <%= form.text_field :categories %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

B3/app/views/posts/_search_bar.html.erb
<div class="row">
    <div class="col-sm-9 col-lg-8 col-lg-offset-2">
        <%= form_tag search_posts_path , :method => :get do %>
            <div class="input-group">
                <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="查询文章...">
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        <% end %>
    </div>
</div>

B3/app/views/posts/category.html.erb
<h3><%= @category %></h3>
<table width="100%"; style="table-layout: fixed;">
  <thead>
    <tr>
      <th>作者</th>
      <th>标题</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.reverse_each do |post| %>
      <tr>
        <td><%= post.postable.username %></td>
        <td><%= post.title %></td>
        <div class="innerCtn">
<span class="mui-ellipsis-3"><p><td style="white-space:nowrap;overflow: hidden;text-overflow:ellipsis"><%= post.body %></td></span>
</p></div>
        <td><%= link_to '阅读全文', post %></td>
      </tr>
    <% end %>
    <%= will_paginate @posts %>
  </tbody>
</table>

B3/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %>

<%= link_to 'Back', posts_path %>

B3/app/views/posts/index.html.erb
<h3>欢迎 <%= @username %></h3>
<table width="100%"; style="table-layout: fixed;">
  <thead>
    <tr>
      <th>作者</th>
      <th>标题</th>
      <th>内容</th>
      <th>分类</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.postable.username %></td>
        <td><%= post.title %></td>
        <div class="innerCtn">
<span class="mui-ellipsis-3"><p><td style="white-space:nowrap;overflow: hidden;text-overflow:ellipsis"><%= post.body %></td></span>
</p></div>

        <td><%= post.categories %></td>
        <td><%= link_to '阅读全文', post %></td>
      </tr>
    <% end %>
    <%= will_paginate @posts %>
  </tbody>
</table>

B3/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

B3/app/views/posts/search.html.erb
<div class="post-box">
  <div class="container">
    <!--=== 搜索结果，没有符合条件的数据 ===-->
    <% if @query_string.blank? %>
      <h2 class="search-info-title">搜索信息不能为空，请输入关键字搜索</h2>
    <% elsif @posts.blank?%>
      <br>
        <h2 class="search-info-title">亲，没有搜索到文章哦，要不换个关键词试试？</h2>
    <% else %>
    <!--=== 搜索结果，有符合条件的数据 ===-->
    <!--=== 搜索內容 ===-->
    <div class='row'>
       <% @posts.each do |post| %>
         <div class='col-xs-12 col-sm-4 col-md-3 post-content'>
           <div class="post-body">
            <p><%= link_to(render_highlight_content(post,@query_string), post_path(post)) %></p>
            <p><%= sanitize post.body %></p>
           </div>
         </div>
         <% end %>
       </div>
       <div class="page-box">
         <%= will_paginate @products, renderer: BootstrapPagination::Rails, :previous_label => t('previous-label'), :next_label => t('next-label') %>
       </div>
    <% end %>
  </div>
</div>

B3/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><%= @post.title %></h1>
</p>

<p>
  <h4><strong>作者:</strong>
  <%= @post.postable.username %></h4>
</p>

<p>
  <%= sanitize @post.body %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @post.categories %>
</p>

<%= link_to '返回', posts_path %>
<br><br><br>
<%= form_for(:comment, url: comment_create_path) do |form| %>
<div class="field">
   <%= form.text_area :message, size: "60x12" %>
   <%= form.hidden_field :post_id,:value => @post.id  %>
   <%= form.hidden_field :commentable_id, :value => @post.id %>
   <%= form.hidden_field :commentable_type, :value => "Post" %>
   <%= form.hidden_field :user_id, :value => session[:user_id] %>
</div>
<div class="actions">
    <%= form.submit "发表评论" %>
  </div>
  <% end %>
<br>
<h3>评论区</h3>
<% @comments.each do |comment| %>
<b>用户<%= User.find(comment.user_id).username %>:</b><%= comment.message %><br>
<% end %>
<br><br><br><br><br><br>

B3/app/views/posts/time.html.erb
<p id="notice"><%= notice %></p>
<table width="100%"; style="table-layout: fixed;">
  <thead>
    <tr>
      <th>作者</th>
      <th>标题</th>
      <th>内容</th>
      <th>分类</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.reverse_each do |post| %>
      <tr>
        <td><%= post.postable.username %></td>
        <td><%= post.title %></td>
        <div class="innerCtn">
<span class="mui-ellipsis-3"><p><td style="white-space:nowrap;overflow: hidden;text-overflow:ellipsis"><%= post.body %></td></span>
</p></div>

        <td><%= post.categories %></td>
        <td><%= link_to '阅读全文', post %></td>
      </tr>
    <% end %>
    <%= will_paginate @posts %>
  </tbody>
</table>