B3/config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      get :search
    end

    get 'category(/:name)', name: /[a-zA-Z0-9]+/ ,on: :collection, to: 'posts#category', as: :category
    get 'time(/:month)', month: /[0-9]+/, on: :collection, to: 'posts#time', as: :time
  end
  root 'posts#index'


  get 'users/register',  to: 'users#register', as: :user_register
  post 'users/register', to: 'users#create'
  get 'users/login', to: 'users#new', as: :user_login
  post 'users/login', to: 'users#login'
  get 'users/personal_page', to: 'users#personal_page', as: :personal_page
  delete 'users/logout', to: 'users#destroy', as: :user_logout

  get 'admins/register', to: 'admins#register', as: :admin_register
  post 'admins/register', to: 'admins#create'
  get 'admins/login', to: 'admins#new', as: :admin_login
  post 'admins/login', to: 'admins#login'
  delete 'admins/logout', to: 'admins#destroy', as: :admin_logout
  get 'admins/lock', to: 'admins#lock', as: :admin_lock
  get 'admins/my_check', to: 'admins#my_check', as: :my_check
  get 'admins/check_index', to: 'admins#check_index', as: :check_index
  post 'admins/check', to: 'admins#check', as: :check
  get 'admins/check_show/(/:post_id)', post_id: /[0-9]+/, to: 'admins#check_show',as: :check_show

  post 'comments/create', to: 'comments#create', as: :comment_create
  get 'comments/index', to: 'comments#index', as: :comments
  post 'comments/check', to: 'comments#check', as: :check_comments

  post 'feedbacks/create', to: 'feedbacks#create', as: :feedback_create
  get 'feedbacks/index', to: 'feedbacks#index', as: :feedbacks

end

B3/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  self.per_page = 10
  validates :message, length: {
    minimum: 3
  }
end

B3/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user_login, only:[:create]
  before_action :require_admin_login, only:[:index]

  def index
    @comments = Comment.where.not(comment_check: true).paginate(page: params[:page])
    render layout: 'admin_check'
  end

  def check
    @comment = Comment.find(params[:comment][:id])
    if params[:comment][:check] == "true"
      @comment.comment_check = true
    else
      @comment.comment_check = false
    end
    if @comment.save
      redirect_to comments_path
    end
  end

  def create
    if session[:user_id]
      @comment = Comment.create(comment_params)
      redirect_back(fallback_location: root_path)
    else
      redirect_to user_login_path
    end
  end
  private
  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :message, :comment_check, :commentable_id, :commentable_type)
  end

  def require_admin_login
    unless session[:admin_id]
      redirect_to admin_login_path
    end
  end

  def require_user_login
    unless session[:user_id]
      redirect_to user_login_path
    end
  end
end

B3/app/helpers/comments_helper.rb
module CommentsHelper
end

B3/app/views/comments/index.html.erb
<h3><%= @notice %></h3>
<table width="100%"; style="table-layout: fixed;">
  <thead>
    <tr>
      <th>作者</th>
      <th>留言</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= User.find(comment.user_id).username %></td>
        <td><%= comment.message %></td>
        <td><%= form_for(:comment, url: check_comments_path) do |f| %>
          <div class="field">
          <%= f.hidden_field :check, :value => true %>
          <%= f.hidden_field :id, :value => comment.id %>
        </div>
        <div class="actions">
          <%= f.submit "通过"%>
        </div>
        <% end %></td>
        <td><%= form_for(:comment, url: check_comments_path) do |f| %>
          <div class="field">
          <%= f.hidden_field :check, :value => false %>
          <%= f.hidden_field :id, :value => comment.id %>
        </div>
        <div class="actions">
          <%= f.submit "不通过"%>
        </div>
        <% end %></td>
      </tr>
    <% end %>
    <%= will_paginate @comments %>
  </tbody>
</table>