B3/config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      get :search
    end

    get 'category(/:name)', name: /[a-zA-Z0-9]+/ ,on: :collection, to: 'posts#category', as: :category
    get 'time(/:month)', month: /[0-9]+/, on: :collection, to: 'posts#time', as: :time
  end
  root 'posts#index'


  get 'users/register',  to: 'users#register', as: :user_register
  post 'users/register', to: 'users#create'
  get 'users/login', to: 'users#new', as: :user_login
  post 'users/login', to: 'users#login'
  get 'users/personal_page', to: 'users#personal_page', as: :personal_page
  delete 'users/logout', to: 'users#destroy', as: :user_logout

  get 'admins/register', to: 'admins#register', as: :admin_register
  post 'admins/register', to: 'admins#create'
  get 'admins/login', to: 'admins#new', as: :admin_login
  post 'admins/login', to: 'admins#login'
  delete 'admins/logout', to: 'admins#destroy', as: :admin_logout
  get 'admins/lock', to: 'admins#lock', as: :admin_lock
  get 'admins/my_check', to: 'admins#my_check', as: :my_check
  get 'admins/check_index', to: 'admins#check_index', as: :check_index
  post 'admins/check', to: 'admins#check', as: :check
  get 'admins/check_show/(/:post_id)', post_id: /[0-9]+/, to: 'admins#check_show',as: :check_show

  post 'comments/create', to: 'comments#create', as: :comment_create
  get 'comments/index', to: 'comments#index', as: :comments
  post 'comments/check', to: 'comments#check', as: :check_comments

  post 'feedbacks/create', to: 'feedbacks#create', as: :feedback_create
  get 'feedbacks/index', to: 'feedbacks#index', as: :feedbacks

end

B3/app/views/layouts/admin_check.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>审核系统</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <header class="navbar">
    <div class="navbar navbar-light" style="background-color: #e3f2fd;text-align: center;">
    <div class="container">
      <ul class="nav nav-pills" style="display: inline-block;float: none;">
        <li class="active"><%=link_to'文章审核', check_index_path %></li>
        <li><%=link_to'留言审核', comments_path%></li>
        <li><%=link_to'意见反馈', feedbacks_path%></li>

        <li class="dropdown">
      		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
      			<span class="caret"></span>
      		</a>
      		<ul class="dropdown-menu">
            <li><%=link_to'个人中心', my_check_path %></li>
            <li><%= link_to '退出登录', admin_logout_path, method: :delete %>
      		</ul>
      	</li>
        </ul>
      </div>
     </div>
     </header>
  </head>
  <body><div class="container">
    <div class="col-md-4" box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;>
    </div>
    <div class="col-md-8" box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;>
    <%= yield %></div>
  </body>
  </html>

B3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>博客系统</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <header class="navbar">
    <div class="navbar navbar-light" style="background-color: #e3f2fd;text-align: center;">
    <div class="container">
      <ul class="nav nav-pills" style="display: inline-block;float: none;">
        <li class="active"><a href="/posts">首页</a></li>
        <li><%=link_to'Essay', category_posts_path("Essay")%></li>
        <li><%=link_to'Ruby', category_posts_path("Ruby")%></li>

        <li class="dropdown">
      		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
      			<span class="caret"></span>
      		</a>
      		<ul class="dropdown-menu">
            <li><%=link_to'个人中心', personal_page_path %></li>
            <li><%= link_to '退出登录', user_logout_path, method: :delete %>
      		</ul>
      	</li>
        </ul>
      </div>
     </div>
     </header>
  </head>

  <body>
    <div class="container">
      <div class="col-md-8" box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;>
    <%= yield %>
  </div>
  <div class="col-md-4" box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;>
        <br>
        <%= render :partial => "posts/search_bar" %><br>
        <ul><h3>&#8195;&#8195;&#8195;&#8195;&#8195;<%= link_to '写文章', new_post_path %><h3></ul>
          <br><ul><h3>&#8195;&#8195;&#8195;&#8195;按发表时间查看文章</h3></ul>
          <ul><h4>&#8195;&#8195;&#8195;&#8195;&#8195;<%= link_to '2018.8', time_posts_path(8) %></h4></ul>
          <ul><h4>&#8195;&#8195;&#8195;&#8195;&#8195;<%= link_to '2018.7', time_posts_path(7) %></h4></ul>
          <ul><h4>&#8195;&#8195;&#8195;&#8195;&#8195;<%= link_to '2018.6', time_posts_path(6) %></h4></ul>
          <br><br><ul><ul>
            <%= form_for(:feedback, url: feedback_create_path) do |form| %>
            <div class="field">
            <%= form.text_area :content, size: "30x4"%>
            </div>
            <div class="actions">
            <h3><%= form.submit "发表反馈" %>
            </div>
            <% end %></h3></ul></ul>
      </div>
    </div>
  </body>
</html>

B3/app/views/layouts/user_admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>