B3/config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      get :search
    end

    get 'category(/:name)', name: /[a-zA-Z0-9]+/ ,on: :collection, to: 'posts#category', as: :category
    get 'time(/:month)', month: /[0-9]+/, on: :collection, to: 'posts#time', as: :time
  end
  root 'posts#index'


  get 'users/register',  to: 'users#register', as: :user_register
  post 'users/register', to: 'users#create'
  get 'users/login', to: 'users#new', as: :user_login
  post 'users/login', to: 'users#login'
  get 'users/personal_page', to: 'users#personal_page', as: :personal_page
  delete 'users/logout', to: 'users#destroy', as: :user_logout

  get 'admins/register', to: 'admins#register', as: :admin_register
  post 'admins/register', to: 'admins#create'
  get 'admins/login', to: 'admins#new', as: :admin_login
  post 'admins/login', to: 'admins#login'
  delete 'admins/logout', to: 'admins#destroy', as: :admin_logout
  get 'admins/lock', to: 'admins#lock', as: :admin_lock
  get 'admins/my_check', to: 'admins#my_check', as: :my_check
  get 'admins/check_index', to: 'admins#check_index', as: :check_index
  post 'admins/check', to: 'admins#check', as: :check
  get 'admins/check_show/(/:post_id)', post_id: /[0-9]+/, to: 'admins#check_show',as: :check_show

  post 'comments/create', to: 'comments#create', as: :comment_create
  get 'comments/index', to: 'comments#index', as: :comments
  post 'comments/check', to: 'comments#check', as: :check_comments

  post 'feedbacks/create', to: 'feedbacks#create', as: :feedback_create
  get 'feedbacks/index', to: 'feedbacks#index', as: :feedbacks

end

B3/app/views/admins/check_index.html.erb
<h3><%= @notice %></h3>
<table width="100%"; style="table-layout: fixed;">
  <thead>
    <tr>
      <th>作者</th>
      <th>标题</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.postable.username %></td>
        <td><%= post.title %></td>
        <td><%= link_to '阅读全文', check_show_path(post.id) %></td>
      </tr>
    <% end %>
    <%= will_paginate @posts %>
  </tbody>
</table>

B3/app/views/admins/check_show.html.erb
<p>
  <h1><%= @post.title %></h1>
</p>

<p>
  <h4><strong>作者:</strong>
  <%= @post.postable.username %></h4>
</p>

<p>
  <%= sanitize @post.body %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @post.categories %>
</p>

<%= form_for(:admin, url:check_path) do |f| %>
<div class="field">
  <%= f.hidden_field :post_id, :value => @post.id %>
  <%= f.hidden_field :post_check, :value => true %>
</div>
<div class="actions">
  <%= f.submit "通过" %>
</div>
<% end %>

<%= form_for(:admin, url:check_path) do |f| %>
<div class="field">
  <%= f.hidden_field :post_id, :value => @post.id %>
  <%= f.hidden_field :post_check, :value => false %>
</div>
<div class="actions">
  <%= f.submit "不通过" %>
</div>
<% end %>
<br>
<%= link_to '返回', posts_path %>
<br><br><br>

B3/app/views/admins/lock.html.erb
<center><h3><%= @notice %></h3></center>

B3/app/views/admins/login.html.erb
<div class="container"style="padding: 200px 300px 100px;">
	<div class="jumbotron">
    <center><h3><%= @notice %></h3></center>
		<center><h4>管理系统</h4></center><br>
<%= form_for(:admin, url: admin_login_path) do |form| %>

<div class="field">
    <center>
  <%= form.label :用户名 %><br>
  <%= form.text_field :admin_name %><br>
  </center>
</div>
<br>
<div class="field">
  <center>
  <%= form.label :密码 %><br>
  <%= form.password_field :password %>
</center>
</div>
<br>
<div class="actions">
  <center>
  <%= form.submit "登录" %>
</center>
</div>
<br>
<div class="field">
  <center>
  <%= link_to '注册', admin_register_path %>
</center>
</div>
<% end %>
</div>
</div>

B3/app/views/admins/my_check.html.erb
<h3>欢迎，<%= @admin_name %></h3>
<h3>我的审核</h3>
<table width="100%"; style="table-layout: fixed;">
  <thead>
    <tr>
      <th>标题</th>
      <th>内容</th>
      <th>分类</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.reverse_each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <div class="innerCtn">
<span class="mui-ellipsis-3"><p><td style="white-space:nowrap;overflow: hidden;text-overflow:ellipsis"><%= post.body %></td></span>
</p></div>

        <td><%= post.categories %></td>
        <td><%= link_to '阅读全文', check_show_path(post.id) %></td>
        <td><%= link_to '编辑', edit_post_path(post) %></td>
        <td><%= link_to '删除', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
<%= will_paginate @posts %>
  </tbody>
</table>

B3/app/views/admins/register.html.erb
<div class="container"style="padding: 200px 300px 100px;">
	<div class="jumbotron">
    <center><h3><%= @notice %></h3></center>
    <center><h4>管理系统</h4></center><br>
<%= form_for(:admin, url: admin_register_path) do |form| %>
<div class="field">
  <center>
  <%= form.label :用户名 %><br>
  <%= form.text_field :admin_name %><br>
</center>
</div>
<br>
<div class="field">
  <center>
  <%= form.label :密码 %><br>
  <%= form.password_field :password %>
</center>
</div>
<br>
<div class="actions">
  <center>
  <%= form.submit "注册" %>
</center>
</div>
<br>
<div class="field">
  <center>
  <%= link_to '登录', admin_login_path %>
</center>
</div>
<% end %>
</div>
</div>